image: bluesquall/lcm:1.3.1

pipelines:
  default:
    - step:
        script:
          - autoreconf --install
          - ./configure
          - make
          - make check
          - make distcheck
          - find . -type f -iname "*.xz" -print0 | while read -d $'\0' -r file; do curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"$file"; done
