image: bluesquall/lcm:1.3.1

pipelines:
  default:
    - step:
        name: build and check
        script:
          - autoreconf --install
          - ./configure
          - make
          - make check
          - make distcheck
  tags:
    '*':
    - step:
        name: build and POST
        script:
          - autoreconf --install
          - ./configure
          - make
          - make check
          - make distcheck
          - find . -type f -iname "*.xz" -print0 | while read -d $'\0' -r file; do curl --user "${BITBUCKET_REPO_OWNER}:${PIPELINE_APP_PASSWORD}" -X POST "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"$file"; done
